language: node_js
node_js:
  - "8"
  - "7"
os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install cairo pango; fi

script:
  - npm test
